#!/usr/local/bin/node

var request = require('request');
var cheerio = require('cheerio');
var fs = require('fs');
var arg = process.argv.slice(2);
var req_headers = {'User-Agent':"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.9.2490.86 Safari/537.36"};
var target = "https://www.ptt.cc/bbs/";

var tokenizor = require("nodejieba");
tokenizor.load({dict:'./dict.txt'});

var delay = 0;
var board = arg[1] || 'politics';
var crawltype = arg[0]; // page, article, link

var XLSX = require('xlsx');

/* 拆詞 */

var analysis = function(text){
  tokens = tokenizor.tag(text);
  if(crawltype=='page'){
    merge(tokens);
  }
  else
  {
    return analysize_article(tokens);
  }
}

if(crawltype == 'page' || crawltype == 'article'){
  /* 導入部份，按參數 1 指定看板，從 index 知道最後一頁的頁數，這裹沒有做足夠的防誤。 */
  request({url:target+board+'/',headers:req_headers},function(e,r,html){
    if(!e && r.statusCode == 200) {
      var $ = cheerio.load(html);
      /* get link of last - 1 page as in index.html */
      var lastpage = $('.btn-group.pull-right a')[1].attribs.href;

      /* cut the number part and get lastpage number */
      var lastpage_no = parseInt(/(\d)+\.html$/.exec(lastpage)[0],10) + 1;
      //console.log(lastpage_no);

      }else console.log(e,r.statusCode);

    var MaxPage = arg[2] || 10;
    if(MaxPage > lastpage_no) MaxPage = lastpage;
    for(page=lastpage_no;page>lastpage_no-MaxPage;page--){
      get_links(page);
    }
  });
}


/* 疏理文章的連結。即是在爬... 而且沒有理會 推薦數、板主保留(M)等資料
   留意這裹用了不可靠的順序比較去除掉置底文。 */

var get_links = function(page){
  request({url:target+board+'/index'+page+'.html',headers:req_headers},function(e,r,html){

  if(!e && r.statusCode == 200){
    var $ = cheerio.load(html);
    var curlink = "";
    $('.r-list-container div a').each(function(i,el){
      var href = el.attribs.href.substr(5);
      if(curlink > href) return;
      curlink = href;

      /* 跑太快的話，會出現 503 代表 ptt web 伺服器吃不消在哭哭，不要欺負人啦。 */
      setTimeout(function(){get_context(target+href);},delay*100);
      delay++;
    })
  }else console.log('pageError',e,r.statusCode,page);
 })
}

/* 讀取文章內容。
   沒有理會標題、作者、日期、簽名檔、推文等等... 反正為了示範一切從簡 
   正常來說這些資要放到 local 緩存，那就不用暴力爬文了。
   */


var get_context = function(link){
  request({url:link,headers:req_headers},function(e,r,html){
    if(!e && r.statusCode == 200){
      //console.log(link);
        var main_text = "";
        var $ = cheerio.load(html);
        var children = $('#main-content')[0].children;
        for(child in children){
          if(children[child].type != 'text') continue
          var text = children[child].data.split('\n');

          for(t in text){
            if (text[t] == "--") break;
            main_text += text[t];
          }
        }

        if(main_text){
          console.log(link);
          analysis(main_text);
        }else{
          console.log('notext'+link);
        }
    }else console.log('pageError',e,r.statusCode,link);
  })
}

if(crawltype == 'link'){
  get_context(arg[1]);
}



/* 文章分析 */

var analysize_article = function(article){
  var article_noun= {};
  var article_pos_adj= {};
  var article_neg_adj= {};

  /* 疏理內文分類比重 */
  var inner =  {kmt:0,dpp:0,pfp:0};

  /* 疏理正負面詞比重 */
  var pn = {pos:0,neg:0};

  var type ='';

  for(e in article){
    var o = article[e].split(':');
    var i = o[0];
    var j = o[1];
    switch(j){
      case 'pos':
        pn[j]++;
        type ='pos-adj';  
        break;
      case 'neg':
        pn[j]++;
        type ='neg-adj';  
        break;
      case 'kmt':
      case 'dpp':
      case 'pfp':
        inner[j]++;
        type ='noun';  
        break;
      default:
        continue;
    }

    if(type=='noun'){
      if(!article_noun[i]){
        article_noun[i] = 1;
      }else{
        article_noun[i]++;
      }
    }
    else if(type=='pos-adj'){
      if(!article_pos_adj[i]){
        article_pos_adj[i] = 1;
      }else{
        article_pos_adj[i]++;
      }
    }
    else if(type=='neg-adj'){
      if(!article_neg_adj[i]){
        article_neg_adj[i] = 1;
      }else{
        article_neg_adj[i]++;
      }
    }
  }

  /* 沒有管理同義詞 */
  /* 沒有智慧和訓練可言，若認真一點可以架一個 bp rnn */
  var point = (pn.pos >= pn.neg) ? 1 : -1;
  var highest_cat = '';
  var highest_cnt= 0;
  for(cat in inner){
    if(inner[cat]>highest_cnt)
    {
      highest_cnt = inner[cat];
      highest_cat = cat;
    }
  }

  console.log('名詞出現次數:');
  console.log(article_noun);
  console.log('正面形容詞出現次數:');
  console.log(article_pos_adj);
  console.log('負面形容詞出現次數:');
  console.log(article_neg_adj);
  console.log('正負面評分:');
  console.log('此文章主要在講'+highest_cat+'，分數是'+point*highest_cnt);
  console.log();

  var result =
  {
    'main':highest_cat,
    'value':point*highest_cnt,
    'noun':article_noun,
    'pos':article_pos_adj,
    'neg':article_neg_adj
  }

  return result;
}

/* 頁面分析 */

var repo = {};
var cnt = {kmt:0,dpp:0,uni:0};

var merge = function(obj){
  /* 這裹開始改變數名都比較懶了，應該修正到更易讀 */

   /* 疏理內文分類比重 */
  var inner =  {kmt:0,dpp:0,uni:0};

   /* 疏理正負面詞比重 */
  var pn = {pos:0,neg:0};

  for(e in obj){
    var o = obj[e].split(':');
    var i = o[0];
    var j = o[1];
    switch(j){
     case 'pos':
     case 'neg':
      pn[j]++;  
      continue;
     case 'kmt':
     case 'dpp':
     case 'uni':
      inner[j]++;
      break;
     default:
      continue;
    }

    if(!repo[i]){
       repo[i] = 1;
    }else{
       repo[i]++;
    }
  }

  /* 沒有管理同義詞 */
  /* 沒有智慧和訓練可言，若認真一點可以架一個 bp rnn */
  var point = (pn.pos >= pn.neg) ? 1 : -1;
  for(cat in cnt){
    cnt[cat] += point * inner[cat];
  }
}

// 依指定值產生一個xlsx的cell
var create_cell = function(value)
{
  var result =
  {
    't':"s",
    'v':JSON.stringify(value),
    'r':JSON.stringify(value),
    'h':JSON.stringify(value),
    'w':JSON.stringify(value)
  };

  return result;
}

// 把 object 轉成 array
var object_to_array = function(input_object)
{
  var output_array = [];
  //console.log("input_object",JSON.stringify(input_object));

  // 用這種寫法可以把object中所有的屬性遍歷一遍
  for (var pro in input_object)
  {
    //console.log("pro:",pro);
    //console.log("input_object[pro]",input_object[pro]);
    output_array.push([pro, input_object[pro]]);
  }

  return output_array;
}

// 把 array 轉成 object
var array_to_object = function(input_array)
{
  var output_object = {};

  for (var ele in input_array)
  {
    //console.log(JSON.stringify(input_array[ele][1]));
    output_object[input_array[ele][0]] = input_array[ele][1];
  }

  return output_object;
}

var an_array = [];
// 把一個 object 轉成 array，排序後再轉回 object
var sort_object = function(input)
{
  an_array = object_to_array(input);
  an_array.sort(function(a, b) {return b[1] - a[1]});

  return array_to_object(an_array);
}

if(crawltype == 'xlsx')
{
  var workbook = XLSX.readFile('SplitTest2.xlsx');
  var sheet_name = workbook.SheetNames[1];
  var worksheet = workbook.Sheets[sheet_name];

  for(i = 2; i <= 50; i++)
  {
    var read_cell_name = 'M'+i;
    var read_cell = worksheet[read_cell_name];

    if( read_cell === undefined )
    {
      // 如果沒資料就跳過
      continue;
    }
    else
    {
      console.log(JSON.stringify(read_cell));
    }

    var read_cell_value = read_cell.v;
    var result = analysis(read_cell_value);

    var main_cell_name = 'Q'+i;
    worksheet[main_cell_name] = create_cell(result.main);

    var value_cell_name = 'R'+i;
    worksheet[value_cell_name] = create_cell(result.value);

    var noun_cell_name = 'S'+i;
    worksheet[noun_cell_name] = create_cell(sort_object(result.noun));

    var pos_cell_name = 'T'+i;
    worksheet[pos_cell_name] = create_cell(sort_object(result.pos));

    var neg_cell_name = 'U'+i;
    worksheet[neg_cell_name] = create_cell(sort_object(result.neg));
  }

  XLSX.writeFile(workbook, 'out.xlsx');
}

if(crawltype == 'text')
{
  var data = arg[1];
  analysis(data);
}


/* 當所有異步工作完成，才把結算印出 */

process.on('exit',function(){
  if(crawltype=='page'){
    console.log('名詞出現次數:');
    console.log(repo);
    console.log('正負面評分:');
    console.log(cnt);
    process.exit();
  }
})